version: '3'
services:
  db:
    image: postgres:12.4
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - highcairn_volume_db:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PW:-mysecretpassword1234}
  app:
    build: ./app
    links:
      - db
    volumes:
      - ./app:/var/www
    ports:
      - "8000:8000"
  front:
    build: ./front
    volumes:
      - ./front:/var/www
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "${NGINX_PORT:-8888}:80"
    environment:
      TZ: "Asia/Tokyo"

# 事前にdocker volume create --name highcairn_volume_dbを実行すること
volumes:
  highcairn_volume_db:
    external: true