version: '3'
services:
  db:
    image: postgres:12.4
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - highcairn_volume_db:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword1234}
  app:
    build: ./app
    links:
      - db
    volumes:
      - ./app:/var/www
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword1234}
      PASSWORD_SALT: ${PASSWORD_SALT:-mysecretpasswordhash}
      WEB_HOST: ${WEB_HOST:-http://example.com}
  front:
    build: ./front
    volumes:
      - ./front:/var/www
      - /var/www/node_modules
      - /var/www/highcairn/node_modules
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    volumes:
      - ${NGINX_CONF-./nginx/development.conf}:/etc/nginx/conf.d/default.conf
      - ./app/static:/static
    links:
      - app
      - front
    ports:
      - "${NGINX_PORT_SSL:-18888}:443"
      - "${NGINX_PORT:-8888}:80"
    environment:
      TZ: "Asia/Tokyo"
  cron:
    build: ./cron
    links:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword1234}
      
      
# 事前にdocker volume create --name highcairn_volume_dbを実行すること
volumes:
  highcairn_volume_db:
    external: true