# Generated by Django 3.0.6 on 2021-01-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highcairnapp', '0005_auto_20210114_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagethumbnail',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagethumbnail',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='highcairnapp.Image'),
        ),
    ]
